Repository OpenDevicePartnership/mimxrt633s-pac, pull requests merged in 2025-02, with the labels that each got.

#11 Fix repo URL
  Cargo.toml
Labels: bug, documentation

#14 Add valid ESPI port RAM lengths
  patch/espi.yaml
  src/espi/port/ramuse.rs
Labels: enhancement

#13 Patch ADC RESFIFO field D and remove reference to 632
  Cargo.toml
  patch/MIMXRT633S.yaml
  patch/adc.yaml
  patch/toplevel.yaml
  src/adc0/resfifo.rs
  src/lib.rs
Labels: enhancement

#16 espi: PnSTAT: add W1C bits correctly
  Cargo.toml
  patch/espi.yaml
  src/espi/port/stat.rs
Labels: bug

#17 espi: MSTAT: HSTALL is also W1C
  Cargo.toml
  patch/espi.yaml
  src/espi/mstat.rs
Labels: bug

#18 CRC WR_DATA access sizes
  Cargo.toml
  patch/crc.yaml
  src/crc_engine.rs
  src/crc_engine/wr_data16.rs
  src/crc_engine/wr_data32.rs
  src/crc_engine/wr_data8.rs
Labels: bug, breaking change

#21 Patch ctimer ir fields to be W1C
  Cargo.toml
  patch/MIMXRT633S.yaml
  patch/ctimer.yaml
  src/ctimer0/ir.rs
Labels: bug
